spring.application.name=catequeseapi

# MySQL Aiven Produção
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=catequese

# JWT
jwt.secret=${JWT_SECRET:catequese_paroquia_nossa_senhora_da_escada_A9$fQ2@L#r7!MZ%}
jwt.expirationMs=172800000

# Upload limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=40MB

# Tomcat settings
server.tomcat.max-swallow-size=52428800
server.port=${PORT:8080}

gcs.bucket=catequese-escada-storage

# Frontend
spring.web.resources.static-locations=
spring.mvc.static-path-pattern=/public/**

# Logging em produção
logging.level.root=INFO
logging.level.com.catequese=INFO

