spring.application.name=catequeseapi

# Configuração padrão - usar perfil específico (dev ou prod)
# Para desenvolvimento: spring.profiles.active=dev
# Para produção: spring.profiles.active=prod

# JWT
jwt.secret=catequese_paroquia_nossa_senhora_da_escada_A9$fQ2@L#r7!MZ%
jwt.expirationMs=172800000

# Upload limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=40MB

# Tomcat settings
server.tomcat.max-swallow-size=52428800
server.port=${PORT:8080}

gcs.bucket=catequese-escada-storage

# Frontend
spring.web.resources.static-locations=
spring.mvc.static-path-pattern=/public/**


