spring.application.name=catequeseapi

# MariaDB Desenvolvimento Local
# Use variáveis de ambiente para evitar problemas com caracteres especiais
spring.datasource.url=${DEV_DB_URL:jdbc:mariadb://localhost:3306/catequese?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DEV_DB_USER:root}
spring.datasource.password=${DEV_DB_PASSWORD:}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=catequese

# JWT
jwt.secret=catequese_paroquia_nossa_senhora_da_escada_A9$fQ2@L#r7!MZ%
jwt.expirationMs=172800000

# Upload limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=40MB

# Tomcat settings
server.tomcat.max-swallow-size=52428800
server.port=${PORT:8080}

gcs.bucket=catequese-escada-storage

# Frontend
spring.web.resources.static-locations=
spring.mvc.static-path-pattern=/public/**

